baseURL = "https://slides.aarongorka.com/"
languageCode = "en-us"
title = "Aaron's slides"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"
uglyurls = true
enableEmoji = true

[params]
description = "Aaron's slides"

[params.reveal_hugo]
history = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
